### ISSUE TITLE
Updating App Causes App To Be Deleted

### ISSUE THREAD

**Issue by brian-avery** [verizonlabs/hydrogen#35]
Calling put on hydrogen/v1/api/app/ns-portal, instead of updating the app, seems to delete the app. After calling put, if I do a list, the app is no longer present in the list of running applications.

**Comment by thanset** [comment]
@brian-avery ` instead of deleting the app, seems to delete the app. ` Can you clarify what you mean? What type of behavior do you expect on an update event?

Right now it's implemented as launching new task(s), and deleting the "old" application. In this sense it's a basic A-B deployment.

**Comment by brian-avery** [comment]
@thanset Sorry, wrote deleting instead of updating. Basically the behavior that I was seeing is you send an update (even with same config), check the list of running applications, and the app is no longer running. Even after waiting a couple of minutes, the app does not show back up in the list.
