### ISSUE TITLE
API needs to cleanly return data to users

### ISSUE THREAD

**Issue by aaronjwood** [verizonlabs/hydrogen#37]
Currently a string representation of our struct is put into the message. This also might expose too much and cause some confusion for users.

**Comment by thanset** [comment]
This should be done for sure, the protobuf string representation is a bit ugly.  The un-marshalling should be to a JSON representation so it's easy to parse.

**Comment by aaronjwood** [comment]
Just for reference: https://github.com/verizonlabs/hydrogen/pull/40#discussion_r139538465 is where we're at now. Should be easy to extend and add/remove things as we go.
