### ISSUE TITLE
Application failures should trigger an event

### ISSUE THREAD

**Issue by brian-avery** [verizonlabs/hydrogen#39]
Currently, if an app fails to launch enough times, it quietly disappears from the app list. It would be nice to have some sort of a feature so that if an app fails it triggers an event such as emailing the owner of the application to notify them of the failure/cause.

**Comment by thanset** [comment]
@brian-avery absolutely. There was some talk of exposing a list of failed tasks somehow via the API so folks can see what went wrong. This state is kept within the mesos master but isn't exposed via sprint.

**Comment by thanset** [comment]
We can keep track of failed tasks and expose why they failed on a separate API endpoint, or expose that via the status endpoint. @aaronjwood Comments? 

We can mark a task as FAILURE_LIMIT or something of the like as it's status and display that to the user along with the error message from the executor?
